name: Auto Update Sitemap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate sitemap
        run: node generate-sitemap.js

      - name: Configure git
        run: |
          git config --global user.name "sitemap-bot"
          git config --global user.email "sitemap@bot.com"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Commit and push sitemap.xml
        run: |
          git add sitemap.xml
          git commit -m "Update sitemap.xml" || echo "Nothing to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
